---
- name: Install Docker, AWS CLI, eksctl, kubectl
  hosts: jenkins_server
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - unzip
          - apt-transport-https
          - ca-certificates
          - gnupg
          - software-properties-common
        update_cache: yes

    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com | sh
        usermod -aG docker ubuntu
      args:
        executable: /bin/bash

    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install

    - name: Install eksctl
      shell: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        mv /tmp/eksctl /usr/local/bin

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin
